<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Nonaktifkan foreign key checks untuk truncate
        Schema::disableForeignKeyConstraints();
        DB::table('kendaraan')->truncate();
        Schema::enableForeignKeyConstraints();

        $vehicles = [
            // --- 10 Mobil ---
            [
                'namaKendaraan' => 'Toyota Hilux Patroli 01',
                'plat' => 'KT 1234 AB',
                'pemilik' => 'Budi Santoso',
                'merk' => 'Toyota',
                'jenisKendaraan' => 'mobil',
                'penanggungjawab' => 'Budi Santoso',
                'NUP' => '308010401017',
                'unitKerja' => 'Sekwil II / Samarinda',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
            [
                'namaKendaraan' => 'Mitsubishi Pajero Sport',
                'plat' => 'KB 5678 CD',
                'pemilik' => 'Doni Firmansyah',
                'merk' => 'Mitsubishi',
                'jenisKendaraan' => 'mobil',
                'penanggungjawab' => 'Doni Firmansyah',
                'NUP' => '308010401018',
                'unitKerja' => 'Sekwil III / Pontianak',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
            [
                'namaKendaraan' => 'Toyota Avanza Operasional',
                'plat' => 'KH 9101 EF',
                'pemilik' => 'Eka Putri',
                'merk' => 'Toyota',
                'jenisKendaraan' => 'mobil',
                'penanggungjawab' => 'Eka Putri',
                'NUP' => '308010401019',
                'unitKerja' => 'Balai',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
            [
                'namaKendaraan' => 'Isuzu D-Max Lapangan',
                'plat' => 'KT 8877 GH',
                'pemilik' => 'Fajar Nugroho',
                'merk' => 'Isuzu',
                'jenisKendaraan' => 'mobil',
                'penanggungjawab' => 'Fajar Nugroho',
                'NUP' => '308010401020',
                'unitKerja' => 'Sekwil II / Samarinda',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
            [
                'namaKendaraan' => 'Ford Ranger XLT',
                'plat' => 'KB 1122 IJ',
                'pemilik' => 'Gita Wulandari',
                'merk' => 'Ford',
                'jenisKendaraan' => 'mobil',
                'penanggungjawab' => 'Gita Wulandari',
                'NUP' => '308010401021',
                'unitKerja' => 'Sekwil III / Pontianak',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
            [
                'namaKendaraan' => 'Suzuki Ertiga Staff',
                'plat' => 'KH 3344 KL',
                'pemilik' => 'Hadi Prawira',
                'merk' => 'Suzuki',
                'jenisKendaraan' => 'mobil',
                'penanggungjawab' => 'Hadi Prawira',
                'NUP' => '308010401022',
                'unitKerja' => 'Balai',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
            [
                'namaKendaraan' => 'Toyota Fortuner VRZ',
                'plat' => 'KT 5566 MN',
                'pemilik' => 'Admin Sekwil I',
                'merk' => 'Toyota',
                'jenisKendaraan' => 'mobil',
                'penanggungjawab' => 'Admin Sekwil I',
                'NUP' => '308010401023',
                'unitKerja' => 'Sekwil I / Palangka raya',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
            [
                'namaKendaraan' => 'Daihatsu Terios TX',
                'plat' => 'KB 7788 OP',
                'pemilik' => 'Admin Sekwil III',
                'merk' => 'Daihatsu',
                'jenisKendaraan' => 'mobil',
                'penanggungjawab' => 'Admin Sekwil III',
                'NUP' => '308010401024',
                'unitKerja' => 'Sekwil III / Pontianak',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
            [
                'namaKendaraan' => 'Honda HR-V',
                'plat' => 'KH 9900 QR',
                'pemilik' => 'Admin Balai',
                'merk' => 'Honda',
                'jenisKendaraan' => 'mobil',
                'penanggungjawab' => 'Admin Balai',
                'NUP' => '308010401025',
                'unitKerja' => 'Balai',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
            [
                'namaKendaraan' => 'Wuling Almaz',
                'plat' => 'KT 1010 ST',
                'pemilik' => 'Husna Fika',
                'merk' => 'Wuling',
                'jenisKendaraan' => 'mobil',
                'penanggungjawab' => 'Husna Fika',
                'NUP' => '308010401026',
                'unitKerja' => 'Sekwil II / Samarinda',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],

            // --- 10 Motor ---
            [
                'namaKendaraan' => 'Honda CRF Trail 01',
                'plat' => 'KT 2233 UV',
                'pemilik' => 'Citra Lestari',
                'merk' => 'Honda',
                'jenisKendaraan' => 'motor',
                'penanggungjawab' => 'Citra Lestari',
                'NUP' => '308010502011',
                'unitKerja' => 'Sekwil II / Samarinda',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
            [
                'namaKendaraan' => 'Yamaha NMAX Operasional',
                'plat' => 'KH 4455 WX',
                'pemilik' => 'Fajar Nugroho',
                'merk' => 'Yamaha',
                'jenisKendaraan' => 'motor',
                'penanggungjawab' => 'Fajar Nugroho',
                'NUP' => '308010502012',
                'unitKerja' => 'Sekwil I / Palangka raya',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
            [
                'namaKendaraan' => 'Kawasaki KLX 150',
                'plat' => 'KB 6677 YZ',
                'pemilik' => 'Budi Santoso',
                'merk' => 'Kawasaki',
                'jenisKendaraan' => 'motor',
                'penanggungjawab' => 'Budi Santoso',
                'NUP' => '308010502013',
                'unitKerja' => 'Sekwil III / Pontianak',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
            [
                'namaKendaraan' => 'Honda Vario 125',
                'plat' => 'KT 1212 ZA',
                'pemilik' => 'Gita Wulandari',
                'merk' => 'Honda',
                'jenisKendaraan' => 'motor',
                'penanggungjawab' => 'Gita Wulandari',
                'NUP' => '308010502014',
                'unitKerja' => 'Sekwil II / Samarinda',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
            [
                'namaKendaraan' => 'Suzuki Satria F150',
                'plat' => 'KH 3434 BC',
                'pemilik' => 'Hadi Prawira',
                'merk' => 'Suzuki',
                'jenisKendaraan' => 'motor',
                'penanggungjawab' => 'Hadi Prawira',
                'NUP' => '308010502015',
                'unitKerja' => 'Balai',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
            [
                'namaKendaraan' => 'Yamaha WR155R',
                'plat' => 'KB 5656 DE',
                'pemilik' => 'Doni Firmansyah',
                'merk' => 'Yamaha',
                'jenisKendaraan' => 'motor',
                'penanggungjawab' => 'Doni Firmansyah',
                'NUP' => '308010502016',
                'unitKerja' => 'Sekwil III / Pontianak',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
            [
                'namaKendaraan' => 'Honda ADV 160',
                'plat' => 'KT 7878 FG',
                'pemilik' => 'Eka Putri',
                'merk' => 'Honda',
                'jenisKendaraan' => 'motor',
                'penanggungjawab' => 'Eka Putri',
                'NUP' => '308010502017',
                'unitKerja' => 'Balai',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
             [
                'namaKendaraan' => 'Vespa Sprint S',
                'plat' => 'KH 9090 HI',
                'pemilik' => 'Admin Sekwil I',
                'merk' => 'Vespa',
                'jenisKendaraan' => 'motor',
                'penanggungjawab' => 'Admin Sekwil I',
                'NUP' => '308010502018',
                'unitKerja' => 'Sekwil I / Palangka raya',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
             [
                'namaKendaraan' => 'Honda PCX 160',
                'plat' => 'KB 1313 JK',
                'pemilik' => 'Admin Sekwil III',
                'merk' => 'Honda',
                'jenisKendaraan' => 'motor',
                'penanggungjawab' => 'Admin Sekwil III',
                'NUP' => '308010502019',
                'unitKerja' => 'Sekwil III / Pontianak',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
             [
                'namaKendaraan' => 'Kawasaki W175',
                'plat' => 'KT 1414 LM',
                'pemilik' => 'Admin Balai',
                'merk' => 'Kawasaki',
                'jenisKendaraan' => 'motor',
                'penanggungjawab' => 'Admin Balai',
                'NUP' => '308010502020',
                'unitKerja' => 'Balai',
                'statKendaraan' => 'Stand by',
                'kondisi' => 'Baik',
            ],
        ];

        DB::table('kendaraan')->insert($vehicles);
    }
}

