// --- DATA CONTOH ---
// Data diperbanyak menjadi 10 item
const DataAkun = [
  {
    id: "akun-001",
    nama: "Ahmad Subarjo",
    nip: "198503152010121001",
    jabatan: "Kepala Seksi Operasi",
    unit_kerja: "Seksi Wilayah I",
    lokasi: "Samarinda",
    username: "ahmad.s",
    level: "Admin",
  },
  {
    id: "akun-002",
    nama: "Bambang Pamungkas",
    nip: "199007202015031002",
    jabatan: "Staf Lapangan",
    unit_kerja: "Seksi Wilayah II",
    lokasi: "Balikpapan",
    username: "bambang.p",
    level: "User",
  },
  {
    id: "akun-003",
    nama: "Chandra Wijaya",
    nip: "198811052014021003",
    jabatan: "Analis Kehutanan",
    unit_kerja: "Seksi Wilayah I",
    lokasi: "Samarinda",
    username: "chandra.w",
    level: "User",
  },
  {
    id: "akun-004",
    nama: "Dewi Lestari",
    nip: "199201302018032001",
    jabatan: "Kepala Balai",
    unit_kerja: "Pimpinan",
    lokasi: "Balikpapan",
    username: "dewi.l",
    level: "Super Admin",
  },
  {
    id: "akun-005",
    nama: "Eko Prasetyo",
    nip: "199505252020121005",
    jabatan: "Pengemudi",
    unit_kerja: "Umum",
    lokasi: "PPU",
    username: "eko.p",
    level: "User",
  },
  {
    id: "akun-006",
    nama: "Fitriani",
    nip: "199309102019032002",
    jabatan: "Staf Administrasi",
    unit_kerja: "Tata Usaha",
    lokasi: "Banjarmasin",
    username: "fitriani",
    level: "Admin",
  },
  {
    id: "akun-007",
    nama: "Gunawan Santoso",
    nip: "198704122012121004",
    jabatan: "Kepala Seksi Perencanaan",
    unit_kerja: "Perencanaan",
    lokasi: "Pontianak",
    username: "gunawan.s",
    level: "Admin",
  },
  {
    id: "akun-008",
    nama: "Hasanudin",
    nip: "199802202022031001",
    jabatan: "Staf Lapangan",
    unit_kerja: "Seksi Wilayah III",
    lokasi: "Pontianak",
    username: "hasanudin",
    level: "User",
  },
  {
    id: "akun-009",
    nama: "Indah Permatasari",
    nip: "199408182020122003",
    jabatan: "Analis Data",
    unit_kerja: "Perencanaan",
    lokasi: "Samarinda",
    username: "indah.p",
    level: "User",
  },
  {
    id: "akun-010",
    nama: "Joko Susilo",
    nip: "199106012017031006",
    jabatan: "Pengemudi",
    unit_kerja: "Umum",
    lokasi: "Balikpapan",
    username: "joko.s",
    level: "User",
  },
];

export default DataAkun;