export const DataKendaraan = [
  {
    id_kendaraan: "K-001",
    nama_kendaraan: "Fortuner 2.8 GR Sport 4x4",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 4532 XC",
    merk_tipe: "Toyota Fortuner",
    jenis: "Mobil",
    unit_kerja: "Balai",
    lokasi: "Samarinda",
    penanggung_jawab: "Adi",
    kondisi: "Baik",
    nup: "343432",
    status: "Ready",
    id_pajak: "pajak-001",
    tahun_registrasi: "2023",
    berlaku_sampai: "15-09-2025",
    biaya: "Rp 7.850.000",
    status_pembayaran: "Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2023",
    isi_silinder: "2755 cc",
    warna_kb: "Hitam Metalik",
    bahan_bakar: "Solar",
    no_rangka: "MHF1234567890123",
    no_mesin: "2GD1234567",
    no_bpkb: "S09876543",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-002",
    nama_kendaraan: "Hilux Double Cabin 4x4",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 3210 CB",
    merk_tipe: "Toyota Hilux",
    jenis: "Mobil",
    unit_kerja: "Seksi Wilayah 2",
    lokasi: "Samarinda",
    penanggung_jawab: "Eri",
    kondisi: "Rusak",
    nup: "23232",
    status: "Unready",
    id_pajak: "pajak-002",
    tahun_registrasi: "2022",
    berlaku_sampai: "20-05-2025",
    biaya: "Rp 6.200.000",
    status_pembayaran: "Belum Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2022",
    isi_silinder: "2393 cc",
    warna_kb: "Silver Metalik",
    bahan_bakar: "Solar",
    no_rangka: "MHF2345678901234",
    no_mesin: "2GD2345678",
    no_bpkb: "S87654321",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-003",
    nama_kendaraan: "Triton HDX 4x4",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 9052 BV",
    merk_tipe: "Mitsubishi Triton",
    jenis: "Mobil",
    unit_kerja: "Seksi Wilayah 1",
    lokasi: "Palangkaraya",
    penanggung_jawab: "Kano",
    kondisi: "Baik",
    nup: "32323",
    status: "Used",
    id_pajak: "pajak-003",
    tahun_registrasi: "2021",
    berlaku_sampai: "11-11-2026",
    biaya: "Rp 5.950.000",
    status_pembayaran: "Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2021",
    isi_silinder: "2442 cc",
    warna_kb: "Putih",
    bahan_bakar: "Solar",
    no_rangka: "MMB3456789012345",
    no_mesin: "4N153456789",
    no_bpkb: "S76543210",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-004",
    nama_kendaraan: "Avanza 1.5 G",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 1111 AA",
    merk_tipe: "Toyota Avanza",
    jenis: "Mobil",
    unit_kerja: "Seksi Wilayah 3",
    lokasi: "Pontianak",
    penanggung_jawab: "Budi",
    kondisi: "Baik",
    nup: "454545",
    status: "Ready",
    id_pajak: "pajak-004",
    tahun_registrasi: "2024",
    berlaku_sampai: "02-02-2029",
    biaya: "Rp 3.100.000",
    status_pembayaran: "Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2024",
    isi_silinder: "1496 cc",
    warna_kb: "Hitam",
    bahan_bakar: "Bensin",
    no_rangka: "MHK4567890123456",
    no_mesin: "2NRVE4567890",
    no_bpkb: "S65432109",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-005",
    nama_kendaraan: "Pajero Sport Dakar 4x4",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 2222 BB",
    merk_tipe: "Mitsubishi Pajero Sport",
    jenis: "Mobil",
    unit_kerja: "Balai",
    lokasi: "Samarinda",
    penanggung_jawab: "Citra",
    kondisi: "Baik",
    nup: "565656",
    status: "Used",
    id_pajak: "pajak-005",
    tahun_registrasi: "2023",
    berlaku_sampai: "12-08-2028",
    biaya: "Rp 8.200.000",
    status_pembayaran: "Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2023",
    isi_silinder: "2442 cc",
    warna_kb: "Putih",
    bahan_bakar: "Solar",
    no_rangka: "MMBPAJERO123456",
    no_mesin: "4N15PAJERO123",
    no_bpkb: "S11223344",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-006",
    nama_kendaraan: "Kijang Innova Reborn 2.4 G",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 3333 CC",
    merk_tipe: "Toyota Kijang Innova",
    jenis: "Mobil",
    unit_kerja: "Seksi Wilayah 2",
    lokasi: "Samarinda",
    penanggung_jawab: "Dedi",
    kondisi: "Baik",
    nup: "676767",
    status: "Ready",
    id_pajak: "pajak-006",
    tahun_registrasi: "2022",
    berlaku_sampai: "25-04-2027",
    biaya: "Rp 4.750.000",
    status_pembayaran: "Belum Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2022",
    isi_silinder: "2393 cc",
    warna_kb: "Abu-abu Metalik",
    bahan_bakar: "Solar",
    no_rangka: "MHKINNOVA234567",
    no_mesin: "2GDINNOVA234",
    no_bpkb: "S22334455",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-007",
    nama_kendaraan: "Daihatsu Gran Max Pick Up",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 4444 DD",
    merk_tipe: "Daihatsu Gran Max",
    jenis: "Mobil",
    unit_kerja: "Seksi Wilayah 1",
    lokasi: "Palangkaraya",
    penanggung_jawab: "Fani",
    kondisi: "Rusak",
    nup: "787878",
    status: "Unready",
    id_pajak: "pajak-007",
    tahun_registrasi: "2021",
    berlaku_sampai: "10-10-2026",
    biaya: "Rp 2.100.000",
    status_pembayaran: "Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2021",
    isi_silinder: "1495 cc",
    warna_kb: "Hitam",
    bahan_bakar: "Bensin",
    no_rangka: "MHKGRANMAX34567",
    no_mesin: "K3VEGRANMAX345",
    no_bpkb: "S33445566",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-008",
    nama_kendaraan: "Ford Ranger Raptor",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 5555 EE",
    merk_tipe: "Ford Ranger",
    jenis: "Mobil",
    unit_kerja: "Seksi Wilayah 3",
    lokasi: "Pontianak",
    penanggung_jawab: "Gita",
    kondisi: "Baik",
    nup: "898989",
    status: "Ready",
    id_pajak: "pajak-008",
    tahun_registrasi: "2020",
    berlaku_sampai: "05-06-2025",
    biaya: "Rp 9.500.000",
    status_pembayaran: "Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2020",
    isi_silinder: "2198 cc",
    warna_kb: "Oranye",
    bahan_bakar: "Solar",
    no_rangka: "MNBFRANGER45678",
    no_mesin: "PUMA45678",
    no_bpkb: "S44556677",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-009",
    nama_kendaraan: "Isuzu D-Max Rodeo",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 6666 FF",
    merk_tipe: "Isuzu D-Max",
    jenis: "Mobil",
    unit_kerja: "Seksi Wilayah 2",
    lokasi: "Samarinda",
    penanggung_jawab: "Hadi",
    kondisi: "Baik",
    nup: "909090",
    status: "Used",
    id_pajak: "pajak-009",
    tahun_registrasi: "2022",
    berlaku_sampai: "19-03-2027",
    biaya: "Rp 5.800.000",
    status_pembayaran: "Belum Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2022",
    isi_silinder: "2499 cc",
    warna_kb: "Silver",
    bahan_bakar: "Solar",
    no_rangka: "MPAIDMAX56789",
    no_mesin: "4JK1E56789",
    no_bpkb: "S55667788",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-010",
    nama_kendaraan: "Toyota Hiace Commuter",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 7777 GG",
    merk_tipe: "Toyota Hiace",
    jenis: "Mobil",
    unit_kerja: "Balai",
    lokasi: "Samarinda",
    penanggung_jawab: "Ina",
    kondisi: "Baik",
    nup: "121212",
    status: "Ready",
    id_pajak: "pajak-010",
    tahun_registrasi: "2020",
    berlaku_sampai: "10-07-2025",
    biaya: "Rp 4.500.000",
    status_pembayaran: "Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2020",
    isi_silinder: "2494 cc",
    warna_kb: "Silver",
    bahan_bakar: "Solar",
    no_rangka: "MHF5678901234567",
    no_mesin: "2KD5678901",
    no_bpkb: "S54321098",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-011",
    nama_kendaraan: "KLX 150BF",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 2345 BA",
    merk_tipe: "Kawasaki KLX",
    jenis: "Motor",
    unit_kerja: "Seksi Wilayah 1",
    lokasi: "Palangkaraya",
    penanggung_jawab: "Andi",
    kondisi: "Baik",
    nup: "203948",
    status: "Ready",
    id_pajak: "pajak-011",
    tahun_registrasi: "2023",
    berlaku_sampai: "20-03-2026",
    biaya: "Rp 450.000",
    status_pembayaran: "Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2023",
    isi_silinder: "144 cc",
    warna_kb: "Hijau",
    bahan_bakar: "Bensin",
    no_rangka: "MH4KLX150ABCD123",
    no_mesin: "LX150AE123456",
    no_bpkb: "S43210987",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-012",
    nama_kendaraan: "CRF 150L",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 6789 CD",
    merk_tipe: "Honda CRF",
    jenis: "Motor",
    unit_kerja: "Seksi Wilayah 2",
    lokasi: "Samarinda",
    penanggung_jawab: "Budi",
    kondisi: "Baik",
    nup: "203949",
    status: "Used",
    id_pajak: "pajak-012",
    tahun_registrasi: "2022",
    berlaku_sampai: "18-08-2025",
    biaya: "Rp 420.000",
    status_pembayaran: "Belum Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2022",
    isi_silinder: "149 cc",
    warna_kb: "Merah",
    bahan_bakar: "Bensin",
    no_rangka: "MH1CRF150BCDE234",
    no_mesin: "K56F234567",
    no_bpkb: "S32109876",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-013",
    nama_kendaraan: "WR 155 R",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 1122 EF",
    merk_tipe: "Yamaha WR",
    jenis: "Motor",
    unit_kerja: "Seksi Wilayah 3",
    lokasi: "Pontianak",
    penanggung_jawab: "Cahyo",
    kondisi: "Perbaikan",
    nup: "203950",
    status: "Unready",
    id_pajak: "pajak-013",
    tahun_registrasi: "2024",
    berlaku_sampai: "05-01-2029",
    biaya: "Rp 480.000",
    status_pembayaran: "Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2024",
    isi_silinder: "155 cc",
    warna_kb: "Biru",
    bahan_bakar: "Bensin",
    no_rangka: "MH3WR155CDEF345",
    no_mesin: "G3H5E345678",
    no_bpkb: "S21098765",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-014",
    nama_kendaraan: "D-Tracker 150",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 3344 GH",
    merk_tipe: "Kawasaki D-Tracker",
    jenis: "Motor",
    unit_kerja: "Balai",
    lokasi: "Samarinda",
    penanggung_jawab: "Doni",
    kondisi: "Baik",
    nup: "203951",
    status: "Ready",
    id_pajak: "pajak-014",
    tahun_registrasi: "2023",
    berlaku_sampai: "14-02-2028",
    biaya: "Rp 510.000",
    status_pembayaran: "Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2023",
    isi_silinder: "144 cc",
    warna_kb: "Hitam",
    bahan_bakar: "Bensin",
    no_rangka: "MH4DTRACKERDEF45",
    no_mesin: "LX150AEDEF456",
    no_bpkb: "S98765432",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-015",
    nama_kendaraan: "Vario 160",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 5566 IJ",
    merk_tipe: "Honda Vario",
    jenis: "Motor",
    unit_kerja: "Balai",
    lokasi: "Samarinda",
    penanggung_jawab: "Endang",
    kondisi: "Baik",
    nup: "203952",
    status: "Ready",
    id_pajak: "pajak-015",
    tahun_registrasi: "2023",
    berlaku_sampai: "12-12-2025",
    biaya: "Rp 350.000",
    status_pembayaran: "Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2023",
    isi_silinder: "157 cc",
    warna_kb: "Hitam Doff",
    bahan_bakar: "Bensin",
    no_rangka: "MH1VAR160DEFG456",
    no_mesin: "KF46E456789",
    no_bpkb: "S10987654",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-016",
    nama_kendaraan: "CRF 150L",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 7788 KL",
    merk_tipe: "Honda CRF",
    jenis: "Motor",
    unit_kerja: "Seksi Wilayah 1",
    lokasi: "Palangkaraya",
    penanggung_jawab: "Fajar",
    kondisi: "Baik",
    nup: "203953",
    status: "Used",
    id_pajak: "pajak-016",
    tahun_registrasi: "2021",
    berlaku_sampai: "09-09-2026",
    biaya: "Rp 410.000",
    status_pembayaran: "Belum Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2021",
    isi_silinder: "149 cc",
    warna_kb: "Merah Putih",
    bahan_bakar: "Bensin",
    no_rangka: "MH1CRF150EFG567",
    no_mesin: "K56F567890",
    no_bpkb: "S87654321",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-017",
    nama_kendaraan: "KLX 150BF",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 9900 MN",
    merk_tipe: "Kawasaki KLX",
    jenis: "Motor",
    unit_kerja: "Seksi Wilayah 2",
    lokasi: "Samarinda",
    penanggung_jawab: "Guntur",
    kondisi: "Rusak",
    nup: "203948",
    status: "Unready",
    id_pajak: "pajak-017",
    tahun_registrasi: "2022",
    berlaku_sampai: "22-07-2027",
    biaya: "Rp 440.000",
    status_pembayaran: "Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2022",
    isi_silinder: "144 cc",
    warna_kb: "Hitam",
    bahan_bakar: "Bensin",
    no_rangka: "MH4KLX150FGH678",
    no_mesin: "LX150AEFGH678",
    no_bpkb: "S76543210",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-018",
    nama_kendaraan: "Yamaha NMAX Connected",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 1212 OP",
    merk_tipe: "Yamaha NMAX",
    jenis: "Motor",
    unit_kerja: "Balai",
    lokasi: "Samarinda",
    penanggung_jawab: "Hilda",
    kondisi: "Baik",
    nup: "203955",
    status: "Ready",
    id_pajak: "pajak-018",
    tahun_registrasi: "2022",
    berlaku_sampai: "07-06-2025",
    biaya: "Rp 410.000",
    status_pembayaran: "Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2022",
    isi_silinder: "155 cc",
    warna_kb: "Abu-abu",
    bahan_bakar: "Bensin",
    no_rangka: "MH3NMAX155EFGH567",
    no_mesin: "E3R8E567890",
    no_bpkb: "S09876543",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-019",
    nama_kendaraan: "WR 155 R",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 3434 QR",
    merk_tipe: "Yamaha WR",
    jenis: "Motor",
    unit_kerja: "Seksi Wilayah 3",
    lokasi: "Pontianak",
    penanggung_jawab: "Irfan",
    kondisi: "Baik",
    nup: "203956",
    status: "Used",
    id_pajak: "pajak-019",
    tahun_registrasi: "2023",
    berlaku_sampai: "30-10-2028",
    biaya: "Rp 490.000",
    status_pembayaran: "Belum Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2023",
    isi_silinder: "155 cc",
    warna_kb: "Hitam Biru",
    bahan_bakar: "Bensin",
    no_rangka: "MH3WR155GHI789",
    no_mesin: "G3H5EGHI789",
    no_bpkb: "S65432109",
    warna_tnkb: "Hitam",
  },
  {
    id_kendaraan: "K-020",
    nama_kendaraan: "Honda ADV 160",
    nama_pemilik: "Biro Umum Setda Prov Kaltim",
    plat: "KT 5656 ST",
    merk_tipe: "Honda ADV",
    jenis: "Motor",
    unit_kerja: "Seksi Wilayah 2",
    lokasi: "Samarinda",
    penanggung_jawab: "Jamil",
    kondisi: "Baik",
    nup: "203957",
    status: "Ready",
    id_pajak: "pajak-020",
    tahun_registrasi: "2024",
    berlaku_sampai: "16-04-2029",
    biaya: "Rp 520.000",
    status_pembayaran: "Lunas",
    alamat_stnk: "Jl. Gajah Mada No. 1, Samarinda",
    tahun_pembuatan: "2024",
    isi_silinder: "157 cc",
    warna_kb: "Merah Doff",
    bahan_bakar: "Bensin",
    no_rangka: "MH1ADV160HIJ890",
    no_mesin: "KF48EHIJ890",
    no_bpkb: "S54321098",
    warna_tnkb: "Hitam",
  },
];

export default DataKendaraan;
