const DataLaporan = [
  {
    id: "laporan-001",
    nama_mobil: "Toyota Fortuner",
    plat: "KT 4532 XC",
    merk: "Toyota",
    lokasi_barang: "Balikpapan",
    unit_kerja: "Operasional PPLH",
    penanggung_jawab: "Adi",
    peminjam: "Dodi",
    tgl_pinjam: "01-08-2025",
    rencana_kembali: "08-08-2025",
    tgl_kembali: null,
    kondisi: "Baik",
    status: "Dipinjam",
  },
  {
    id: "laporan-002",
    nama_mobil: "Toyota AE86",
    plat: "KT 3210 CB",
    merk: "Toyota",
    lokasi_barang: "Samarinda",
    unit_kerja: "Tim Survei",
    penanggung_jawab: "Eri",
    peminjam: "Bob",
    tgl_pinjam: "15-07-2025",
    rencana_kembali: "20-07-2025",
    tgl_kembali: "20-07-2025",
    kondisi: "Rusak",
    status: "Dikembalikan",
  },
  {
    id: "laporan-003",
    nama_mobil: "Nissan GTR",
    plat: "KT 9052 BV",
    merk: "Nissan",
    lokasi_barang: "PPU",
    unit_kerja: "Pimpinan",
    penanggung_jawab: "Kano",
    peminjam: "Deni",
    tgl_pinjam: "25-07-2025",
    rencana_kembali: "28-07-2025",
    tgl_kembali: null,
    kondisi: "Baik",
    status: "Terlambat",
  },
  {
    id: "laporan-004",
    nama_mobil: "Honda Civic",
    plat: "KT 1111 AA",
    merk: "Honda",
    lokasi_barang: "Banjarmasin",
    unit_kerja: "Operasional PPLH",
    penanggung_jawab: "Budi",
    peminjam: "Toni",
    tgl_pinjam: "02-08-2025",
    rencana_kembali: "05-08-2025",
    tgl_kembali: null,
    kondisi: "Baik",
    status: "Dipinjam",
  },
  {
    id: "laporan-005",
    nama_mobil: "Mitsubishi Pajero",
    plat: "KT 2222 BB",
    merk: "Mitsubishi",
    lokasi_barang: "Balikpapan",
    unit_kerja: "Pimpinan",
    penanggung_jawab: "Citra",
    peminjam: "Bob",
    tgl_pinjam: "10-06-2025",
    rencana_kembali: "15-06-2025",
    tgl_kembali: "15-06-2025",
    kondisi: "Baik",
    status: "Dikembalikan",
  },
  {
    id: "laporan-006",
    nama_mobil: "Suzuki Ertiga",
    plat: "KT 3333 CC",
    merk: "Suzuki",
    lokasi_barang: "Samarinda",
    unit_kerja: "Operasional PPLH",
    penanggung_jawab: "Dedi",
    peminjam: "Deni",
    tgl_pinjam: "20-07-2025",
    rencana_kembali: "25-07-2025",
    tgl_kembali: "25-07-2025",
    kondisi: "Baik",
    status: "Dikembalikan",
  },
  {
    id: "laporan-007",
    nama_mobil: "Daihatsu Terios",
    plat: "KT 4444 DD",
    merk: "Daihatsu",
    lokasi_barang: "PPU",
    unit_kerja: "Tim Survei",
    penanggung_jawab: "Fani",
    peminjam: "Joko",
    tgl_pinjam: "28-07-2025",
    rencana_kembali: "01-08-2025",
    tgl_kembali: null,
    kondisi: "Rusak",
    status: "Terlambat",
  },
  {
    id: "laporan-008",
    nama_mobil: "Wuling Almaz",
    plat: "KT 5555 EE",
    merk: "Wuling",
    lokasi_barang: "Balikpapan",
    unit_kerja: "Operasional PPLH",
    penanggung_jawab: "Gita",
    peminjam: "Yoga",
    tgl_pinjam: "03-08-2025",
    rencana_kembali: "10-08-2025",
    tgl_kembali: null,
    kondisi: "Baik",
    status: "Dipinjam",
  },
  {
    id: "laporan-009",
    nama_mobil: "Hyundai Creta",
    plat: "KT 6666 FF",
    merk: "Hyundai",
    lokasi_barang: "Banjarmasin",
    unit_kerja: "Pimpinan",
    penanggung_jawab: "Hadi",
    peminjam: "Toni",
    tgl_pinjam: "11-07-2025",
    rencana_kembali: "14-07-2025",
    tgl_kembali: "14-07-2025",
    kondisi: "Baik",
    status: "Dikembalikan",
  },
  {
    id: "laporan-010",
    nama_mobil: "Mazda CX-5",
    plat: "KT 7777 GG",
    merk: "Mazda",
    lokasi_barang: "Samarinda",
    unit_kerja: "Operasional PPLH",
    penanggung_jawab: "Ina",
    peminjam: "Yono",
    tgl_pinjam: "01-08-2025",
    rencana_kembali: "07-08-2025",
    tgl_kembali: null,
    kondisi: "Baik",
    status: "Dipinjam",
  },
];

export default DataLaporan;