const DataMobil = [
  {
    id: "car-001",
    nama_mobil: "Fortuner 2.8 GR Sport 4x4",
    plat: "KT 4532 XC",
    merk: "Toyota Fortuner",
    jenis: "Mobil Pimpinan",
    unit_kerja: "Balai",
    lokasi: "Samarinda",
    penanggung_jawab: "Adi",
    kondisi: "Baik",
    nup: "343432",
    status: "Ready",
  },
  {
    id: "car-002",
    nama_mobil: "Hilux Double Cabin 4x4",
    plat: "KT 3210 CB",
    merk: "Toyota Hilux",
    jenis: "Mobil Patroli",
    unit_kerja: "Seksi Wilayah 2",
    lokasi: "Samarinda",
    penanggung_jawab: "Eri",
    kondisi: "Rusak",
    nup: "23232",
    status: "Unready",
  },
  {
    id: "car-003",
    nama_mobil: "Triton HDX 4x4",
    plat: "KT 9052 BV",
    merk: "Mitsubishi Triton",
    jenis: "Mobil Patroli",
    unit_kerja: "Seksi Wilayah 1",
    lokasi: "Palangkaraya",
    penanggung_jawab: "Kano",
    kondisi: "Baik",
    nup: "32323",
    status: "Used",
  },
  {
    id: "car-004",
    nama_mobil: "Avanza 1.5 G",
    plat: "KT 1111 AA",
    merk: "Toyota Avanza",
    jenis: "Mobil Perjalanan Dinas",
    unit_kerja: "Seksi Wilayah 3",
    lokasi: "Pontianak",
    penanggung_jawab: "Budi",
    kondisi: "Baik",
    nup: "454545",
    status: "Ready",
  },
  {
    id: "car-005",
    nama_mobil: "Pajero Sport Dakar 4x4",
    plat: "KT 2222 BB",
    merk: "Mitsubishi Pajero Sport",
    jenis: "Mobil Pimpinan",
    unit_kerja: "Balai",
    lokasi: "Samarinda",
    penanggung_jawab: "Citra",
    kondisi: "Baik",
    nup: "565656",
    status: "Used",
  },
  {
    id: "car-006",
    nama_mobil: "Kijang Innova Reborn 2.4 G",
    plat: "KT 3333 CC",
    merk: "Toyota Kijang Innova",
    jenis: "Mobil Perjalanan Dinas",
    unit_kerja: "Seksi Wilayah 2",
    lokasi: "Samarinda",
    penanggung_jawab: "Dedi",
    kondisi: "Baik",
    nup: "676767",
    status: "Ready",
  },
  {
    id: "car-007",
    nama_mobil: "Daihatsu Gran Max Pick Up",
    plat: "KT 4444 DD",
    merk: "Daihatsu Gran Max",
    jenis: "Mobil Angkutan Barang",
    unit_kerja: "Seksi Wilayah 1",
    lokasi: "Palangkaraya",
    penanggung_jawab: "Fani",
    kondisi: "Rusak",
    nup: "787878",
    status: "Unready",
  },
  {
    id: "car-008",
    nama_mobil: "Ford Ranger Raptor",
    plat: "KT 5555 EE",
    merk: "Ford Ranger",
    jenis: "Mobil Patroli Khusus",
    unit_kerja: "Seksi Wilayah 3",
    lokasi: "Pontianak",
    penanggung_jawab: "Gita",
    kondisi: "Baik",
    nup: "898989",
    status: "Ready",
  },
  {
    id: "car-009",
    nama_mobil: "Isuzu D-Max Rodeo",
    plat: "KT 6666 FF",
    merk: "Isuzu D-Max",
    jenis: "Mobil Patroli",
    unit_kerja: "Seksi Wilayah 2",
    lokasi: "Samarinda",
    penanggung_jawab: "Hadi",
    kondisi: "Baik",
    nup: "909090",
    status: "Used",
  },
  {
    id: "car-010",
    nama_mobil: "Toyota Hiace Commuter",
    plat: "KT 7777 GG",
    merk: "Toyota Hiace",
    jenis: "Mobil Angkutan Personel",
    unit_kerja: "Balai",
    lokasi: "Samarinda",
    penanggung_jawab: "Ina",
    kondisi: "Baik",
    nup: "121212",
    status: "Ready",
  },
];

export default DataMobil;