const DataMotor = [
  {
    id: "motor-001",
    nama_motor: "KLX 150BF",
    plat: "KT 2345 BA",
    merk: "Kawasaki KLX",
    jenis: "Motor Patroli",
    unit_kerja: "Seksi Wilayah 1",
    lokasi: "Palangkaraya",
    penanggung_jawab: "Andi",
    kondisi: "Baik",
    nup: "203948",
    status: "Ready",
  },
  {
    id: "motor-002",
    nama_motor: "CRF 150L",
    plat: "KT 6789 CD",
    merk: "Honda CRF",
    jenis: "Motor Patroli",
    unit_kerja: "Seksi Wilayah 2",
    lokasi: "Samarinda",
    penanggung_jawab: "Budi",
    kondisi: "Baik",
    nup: "203949",
    status: "Used",
  },
  {
    id: "motor-003",
    nama_motor: "WR 155 R",
    plat: "KT 1122 EF",
    merk: "Yamaha WR",
    jenis: "Motor Patroli",
    unit_kerja: "Seksi Wilayah 3",
    lokasi: "Pontianak",
    penanggung_jawab: "Cahyo",
    kondisi: "Perbaikan",
    nup: "203950",
    status: "Unready",
  },
  {
    id: "motor-004",
    nama_motor: "D-Tracker 150",
    plat: "KT 3344 GH",
    merk: "Kawasaki D-Tracker",
    jenis: "Motor Perjalanan Dinas",
    unit_kerja: "Balai",
    lokasi: "Samarinda",
    penanggung_jawab: "Doni",
    kondisi: "Baik",
    nup: "203951",
    status: "Ready",
  },
  {
    id: "motor-005",
    nama_motor: "Vario 160",
    plat: "KT 5566 IJ",
    merk: "Honda Vario",
    jenis: "Motor Operasional Kantor",
    unit_kerja: "Balai",
    lokasi: "Samarinda",
    penanggung_jawab: "Endang",
    kondisi: "Baik",
    nup: "203952",
    status: "Ready",
  },
  {
    id: "motor-006",
    nama_motor: "CRF 150L",
    plat: "KT 7788 KL",
    merk: "Honda CRF",
    jenis: "Motor Patroli",
    unit_kerja: "Seksi Wilayah 1",
    lokasi: "Palangkaraya",
    penanggung_jawab: "Fajar",
    kondisi: "Baik",
    nup: "203953",
    status: "Used",
  },
  {
    id: "motor-007",
    nama_motor: "KLX 150BF",
    plat: "KT 9900 MN",
    merk: "Kawasaki KLX",
    jenis: "Motor Patroli",
    unit_kerja: "Seksi Wilayah 2",
    lokasi: "Samarinda",
    penanggung_jawab: "Guntur",
    kondisi: "Rusak",
    nup: "203954",
    status: "Unready",
  },
  {
    id: "motor-008",
    nama_motor: "Yamaha NMAX Connected",
    plat: "KT 1212 OP",
    merk: "Yamaha NMAX",
    jenis: "Motor Perjalanan Dinas",
    unit_kerja: "Balai",
    lokasi: "Samarinda",
    penanggung_jawab: "Hilda",
    kondisi: "Baik",
    nup: "203955",
    status: "Ready",
  },
  {
    id: "motor-009",
    nama_motor: "WR 155 R",
    plat: "KT 3434 QR",
    merk: "Yamaha WR",
    jenis: "Motor Patroli",
    unit_kerja: "Seksi Wilayah 3",
    lokasi: "Pontianak",
    penanggung_jawab: "Irfan",
    kondisi: "Baik",
    nup: "203956",
    status: "Used",
  },
  {
    id: "motor-010",
    nama_motor: "Honda ADV 160",
    plat: "KT 5656 ST",
    merk: "Honda ADV",
    jenis: "Motor Perjalanan Dinas",
    unit_kerja: "Seksi Wilayah 2",
    lokasi: "Samarinda",
    penanggung_jawab: "Jamil",
    kondisi: "Baik",
    nup: "203957",
    status: "Ready",
  },
];

export default DataMotor;